.TH fll-installer "3" "January 2015" "fll-installer [OPTIONS]" "User Commands (1)"
.SH NAME
fll-installer - installer backend to install a fullstory/ aptosid based system
.SH SYNOPSIS
.B fll-installer
[\fIOPTIONS\fR]
installer
.SH DESCRIPTION
`fll-installer', is the backend to install a fullstory/ aptosid based live
system to the harddisk.
.TP
\fB\-h\fR|\-\-help
Print this help
.TP
\fB\-d\fR|\-\-debug
Print verbose debugging info
Repeat for more verbose debugging
.TP
\fB\-i\fR|\-\-inotify FIFO
specify inotify FIFO pipe
.SH "SEE ALSO"
.BR install-gui
.SH AUTHOR
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
