.TH FLL-ISO2USB "8" "1th March 2013" "" ""
.SH NAME
\fBfll-iso2usb\fR \- installs a live-CD iso build with the
fll\-tools as a "fromiso" into a USB pen
.SH SYNOPSIS
\fBfll-iso2usb\fR \fI<options>\fR \fI-- <extra_options_to_grub>\fR
.SH DESCRIPTION
installs a \fBsiduction\fR iso-image on a USB-pen, makes the pen
bootable and writes the needed grub files.
.PP
\fBfll-iso2usb\fR creates a partition or uses the first partition from the USB-device, installs
grub and copies the iso into it. When running from the live CD it copies its
contents into the US device.
.PP
\fBfll-iso2usb\fR is intended to be called by the
\fBinstall-usb-gui\fR program but can also be called directly.
.PP
.SH OPTIONS
.TP
\fB\-h|\-\-help\fR
print help screen
.TP
\fB\-D|\-\-device\fR \fI<device>\fR
name of device where to install the "fromiso"
.TP
\fB\-f|\-\-format\fR \fInone|vfat|ext2|ext3\fR
format the device with the given filesystem. When \fInone\fR is given do not format.
.TP
\fB\-I|\-\-iso\fR \fI<iso_file>\fR
name of the iso image to be installed
.TP
\fB\-L|\-\-label\fR \fI<name>\fR
label name to be used for the created partition
.TP
\fB\-n|\-\-noformat\fR
do not format the device, the first partition is used, VFAT or EXT2/EXT3 are accepted.
If the installer formats the partition it uses the whole disk and formats the partition
with EXT3 filesystem.
.TP
\fB\-p|\-\-persist\fR
Install "fromiso" using the "persist" cheatcode. If the device has EXT2/EXT3 filesysten
or gets it when the installer creates the partition then all free place is used for the persist.
When the partition was formatted with VFAT then for the persist option uses at least 100MB 
or at most 2GB (minus one) normally 50% of the free available space.
.TP
\fB\-P|\-\-percent\fR  \fI<%>\fR
Adjust percentage of free space dedicated to the persistent overlay file on
vfat formatted usb media. Value given must be no less than 10 and no more than
90.
.TP
\fB\-t|\-\-test\fR
do not copy the iso image
.TP
\fB\-d|\-\-debug\fR
debug sh code execution
.PP
.SH EXAMPLES
.TP
\fBfll-iso2usb \-D /dev/sdb \-\-iso /home/siduction/siduction.iso \-p  \\\fR
\fB            \-\- toram lang=de tz=Europe/Berlin \fR
.PP
installs the iso image into the USB device sdb. Uses persist and the cheatcodes on the 
grub default command line.
.PP
.SH AUTHOR
This manual page was written originally by Joaquim Boura <x-un-i@berlios.de>
and is modified by Alf Gaida <agaida@siduction.org>
